### PR TITLE
added discord emoji "appwriteblobcatheart"

### PR DESCRIPTION
**Pull request by qwe123coder**
added a this cute
appwriteblobCcatheart

### CODE REVIEW

**Review by Meldiron — CHANGES_REQUESTED** [review]
Looks cool 😎 2 details:

1. White background was not removed properly, there are still some white parts:
CleanShot 2021-10-31 at 09 30 20@2x

2. The whole image is blurred. I tried to add simple shapes on top of it and they look more sharper.

Before:
CleanShot 2021-10-31 at 09 30 09@2x

After:
CleanShot 2021-10-31 at 09 30 13@2x

Can we double-check the quality?

**Comment by qwe123coder** [comment]
k i will fix all of it :)  and make a new pr

**Comment by qwe123coder** [comment]
> 1. The whole image is blurred. I tried to add simple shapes on top of it and they look more sharper.

it is blurd because the img is big when you put it in discord it looks like this 
image

**Comment by qwe123coder** [comment]
hey @Meldiron 
all done new one 
appwriteblobcatheart

**Comment by qwe123coder** [comment]
if you put it in discord its looks good and the small wite thing also gose

**Comment by qwe123coder** [comment]
image

**Comment by Meldiron** [comment]
Unfortunately we would not be able to accept your PR as it does not meet some of our criteria around quality. We love contributions, but we suggest you explore any of our [open issues](https://github.com/appwrite/appwrite/issues). If you have any problem or need help, please join our Discord community: https://appwrite.io/discord and use the #hacktoberfest channel.

**Pull request closed without merging**
