### PR TITLE
add How to import Ghost Blog users to Appwrite

### PR DESCRIPTION
**Pull request by JoyMajumdar2001**
## What does this PR do?

This PR adds a blog on Importing Ghost Blog Users to Appwrite so that one can easily migrate users from Ghost to Appwrite 

## Related PRs and Issues

Issue [4203](https://github.com/appwrite/appwrite/issues/4203)

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

**Yes**

### CODE REVIEW

**Comment by JoyMajumdar2001** [comment]
Hey @adityaoberai , can you please review this PR ?

**Review by gewenyu99 — APPROVED** [review]
Hi @JoyMajumdar2001 ! This is a great write-up.

The content looks good on my side. Let me get @Meldiron to review the code to get a second opinion.

**Comment by gewenyu99** [comment]
Oh, unrelated comment, did you have a chance to run your blog through something like Grammarly to check grammar and spelling to be safe?

**Comment by JoyMajumdar2001** [comment]
@gewenyu99 there were some minor grammatical errors in my blog, now those are fixed 😌

**Review by Meldiron — APPROVED** [review]
The code looks great 😎

**Comment by PineappleIOnic** [comment]
Thank you so much for the PR 🤩. We're adding the `hacktoberfest-accepted` label to ensure this PR counts towards your Hacktoberfest contributions count. With that said, please stay active on this PR to address any comments once you receive a review. Happy Hacktoberfest! 🎃

**Review by gewenyu99 — APPROVED** [review]
Looks good to me <3

Thank you for this awesome blog!

**Review by christyjacob4 — APPROVED** [review]

**Comment by christyjacob4** [comment]
THANK YOU! All changes merged 🥳

Please reach out to me on our [Discord server](https://appwrite.io/discord) if you would like to claim your Appwrite swags! As a way of saying thank you, we would also love to invite you to join the Appwrite organization on GitHub. Please share your GitHub username with us on Discord.  

You can accept the invite by visiting https://github.com/orgs/appwrite/invitation. By joining our team, you will officially be an Appwrite maintainer on GitHub.

You can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite team membership badge will show up on your personal GitHub profile.

Please feel free to look for more PRs you might be interested in helping with on our long list of [Hacktoberfest friendly issues](https://github.com/search?q=org%3Aappwrite+org%3Autopia-php+org%3Aopen-runtimes+label%3Ahacktoberfest+created%3A%3E2021-01-01+state%3Aopen&type=issues&s=updated&o=asc) and help make Appwrite better :)

**Pull request merged**
