### PR TITLE
doc: Added "Appwrite using NGINX as Reverse Proxy" resource

### PR DESCRIPTION
**Pull request by WilfredAlmeida**
Added blog resource on how to deploy Appwrite on VPS server using NGINX as a reverse proxy

### CODE REVIEW

**Review by stnguyen90 — COMMENTED** [review]
Thanks for creating this PR! 🙏🏼 The content is very detailed and helpful! 

Some things are missing, though. 

1. Enabling SSL is very important, and it's best to have HTTPS traffic routed to Appwrite's HTTPS port. Missing that can cause problems with cookies.
2. Without some additional configuration on the traefik container, Appwrite will detect IPs as the Nginx proxy rather than the actual client (for example, in the audit logs or sessions
3. The Nginx config is missing [some directives](https://github.com/appwrite/appwrite/discussions/4329#discussioncomment-4865111) for realtime so the realtime API won't work.

**Comment by WilfredAlmeida** [comment]
Thanks for pointing it out. Will update the blog and let you know for further review.

**Comment by adityaoberai** [comment]
@WilfredAlmeida were you able to make the requested changes?

**Comment by WilfredAlmeida** [comment]
@stnguyen90 

1.
> Enabling SSL is very important, and it's best to have HTTPS traffic routed to Appwrite's HTTPS port. Missing that can cause problems with cookies.

**Comment by adityaoberai** [comment]
@WilfredAlmeida did you get a chance to review the aforementioned points and update your blog?

**Comment by WilfredAlmeida** [comment]
@stnguyen90 @adityaoberai 

No, I don't have any project workload yet to test the changes for traefik & realtime directives.

I'm open to some collaboration on this, as to I can provide an Appwrite instance for someone with an existing project to use it and I can make the changes to get all things working, or you can point out the exact things to add in which I can add in directly.

**Comment by adityaoberai** [comment]
@WilfredAlmeida, you can take this discussion to the [Appwrite Discord server](https://appwrite.io/discord). 
In the meantime, since the collaboration + testing process might take some time, I'll close the PR until you can test the solution and update the blog as needed.

**Pull request closed without merging**
