### PR TITLE
Help Developers by Coding Demo of Appwrite + Next JS

### PR DESCRIPTION
**Pull request by vasucp1207**
- Related to the issue https://github.com/appwrite/appwrite/issues/4225
- Official [repo](https://github.com/vasucp1207/appwrite-chat-app).

### CODE REVIEW

**Comment by PineappleIOnic** [comment]
Thank you so much for the PR 🤩. We're adding the `hacktoberfest-accepted` label to ensure this PR counts towards your Hacktoberfest contributions count. With that said, please stay active on this PR to address any comments once you receive a review. Happy Hacktoberfest! 🎃

**Review by gewenyu99 — CHANGES_REQUESTED** [review]
Looking great, one comment, you do not and should not need to use `uuid()` to generate IDs in Appwrite. 

You can use `ID.unique()` to generate one automatically, just import `ID` from Appwrite.

**Comment by vasucp1207** [comment]
@gewenyu99, I made the required changes.

**Review by gewenyu99 — APPROVED** [review]
Nice work @vasucp1207 !

This PR is looking much better now. Thank you for your contribution ❤️

**Comment by christyjacob4** [comment]
THANK YOU! All changes merged 🥳

Please reach out to me on our [Discord server](https://appwrite.io/discord) if you would like to claim your Appwrite swags! As a way of saying thank you, we would also love to invite you to join the Appwrite organization on GitHub. Please share your GitHub username with us on Discord.  

You can accept the invite by visiting https://github.com/orgs/appwrite/invitation. By joining our team, you will officially be an Appwrite maintainer on GitHub.

You can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite team membership badge will show up on your personal GitHub profile.

Please feel free to look for more PRs you might be interested in helping with on our long list of [Hacktoberfest friendly issues](https://github.com/search?q=org%3Aappwrite+org%3Autopia-php+org%3Aopen-runtimes+label%3Ahacktoberfest+created%3A%3E2021-01-01+state%3Aopen&type=issues&s=updated&o=asc) and help make Appwrite better :)

**Pull request merged**
