### PR TITLE
App System Health for monitor the apps

### PR DESCRIPTION
**Pull request by fernandoamz**
Hey there, Can you take a look to my blogspot? 

[Blogspot](https://dev.to/fernandoamz/appwrites-health-service-3lh7)

It was assigned for me on this [Issue](https://github.com/appwrite/appwrite/issues/2297)

[Source Code](https://github.com/fernandoamz/node-express-server-rest-api)
Happy day!

### CODE REVIEW

**Review by Meldiron — CHANGES_REQUESTED** [review]
For me, the URL shows 404 page not found. Can we double-check the link?

**Comment by fernandoamz** [comment]
This is the link: https://dev.to/fernandoamz/appwrites-health-service-3lh7

**Review by Meldiron — CHANGES_REQUESTED** [review]
Please also link to the GitHub repository related to this article. You can take a look in this README to see how others did it and copy that.

**Comment by fernandoamz** [comment]
Thanks!  I added the source code to repository

**Review by Meldiron — CHANGES_REQUESTED** [review]
Can we please do it in one line? You can copy what has been done for this project, just replace name, description and links:

CleanShot 2021-11-08 at 12 27 01@2x

**Comment by fernandoamz** [comment]
Hy @Meldiron, I made the inline change

**Comment by christyjacob4** [comment]
THANK YOU! All changes merged 🥳

Please reach out to me on our [Discord server](https://appwrite.io/discord) if you would like to claim your Appwrite swags! As a way of saying thank you, we would also love to invite you to join the Appwrite organization on GitHub. Please share your GitHub username with us on Discord.  

You can accept the invite by visiting https://github.com/orgs/appwrite/invitation. By joining our team, you will officially be an Appwrite maintainer on GitHub.

You can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite team membership badge will show up on your personal GitHub profile.

Please feel free to look for more PRs you might be interested in helping with on our long list of [Hacktoberfest friendly issues](https://github.com/search?q=org%3Aappwrite+org%3Autopia-php+is%3Aissue+label%3Ahacktoberfest+created%3A%3E2021-01-01+is%3Aopen&type=issues) and help make Appwrite better :)

**Pull request merged**
