### PR TITLE
Adding Todolist Demo with Appwrite and PReact

### PR DESCRIPTION
**Pull request by vasucp1207**
### I made a todolist using appwrite and preact.
- Reated to this [issue](https://github.com/appwrite/appwrite/issues/4252)
- [Blog](https://3dweb.hashnode.dev/making-a-todolist-with-preact-js-using-appwrite-as-a-backend) of the project on hashnode.

### CODE REVIEW

**Comment by Meldiron** [comment]
@vasucp1207 , thanks for the PR! 🤯 Please give us some time to review it.

**Review by Meldiron — CHANGES_REQUESTED** [review]
I quickly noticed there were too many additions. There looks to be a new `.history` folder made by you - probably your editor did it automatically. Could you please remove that and commit changes?

**Comment by vasucp1207** [comment]
@Meldiron, I deleted the folder.

**Comment by Meldiron** [comment]
Thank you so much for the PR 🤩. We're adding the `hacktoberfest-accepted` label to ensure this PR counts towards your Hacktoberfest contributions count. With that said, please stay active on this PR to address any comments once you receive a review. Happy Hacktoberfest! 🎃

**Pull request merged**
