### PR TITLE
Add budget app in Flutter built with Appwrite

### PR DESCRIPTION
**Pull request by 1995YogeshSharma**
I have created a Sample budget app using Flutter and Appwrite. The app demonstrates appwrite-auth and appwrite database with a simple flutter UI.

I have added both link to the app repository and link to the article for the app.

### CODE REVIEW

**Review by Meldiron — CHANGES_REQUESTED** [review]
The link to the article is not working for me - showing 404 error page. Can we double-check that?

**Comment by 1995YogeshSharma** [comment]
Hi @Meldiron I have updated the link to article (it appears the earlier link was pointing to a draft version), can you please check again?

**Comment by 1995YogeshSharma** [comment]
Hey @Meldiron, please add 'hacktober-accepted' label to the PR!

**Review by Meldiron — CHANGES_REQUESTED** [review]
Few notes:

- Let's Merge these 2 changes together - Let's make one line where we mention both article and the source code. There are examples in README already that you can just copy
- In the article, images seem stretched. Can we double-check that?
- In the article, syntax highlighting does not work. Can we fix that? I believe that is feature of Markdown
- In the repository, can we include section about setting up Appwrite for this project? Collections, rules, functions, project, IDs... Whatever you need to do to start to project on empty Appwrite instance.

**Comment by christyjacob4** [comment]
@1995YogeshSharma closing this PR for now since there has been no activity in quite a long time. Feel free to reopen it when you're ready to start working on it once again. 🙂

**Pull request closed without merging**
