### PR TITLE
Add article on making CMS changes instant using Appwrite real-time service

### PR DESCRIPTION
**Pull request by SakshiUppoor**
Blog post Link: https://sakshiuppoor.hashnode.dev/how-appwrite-real-time-can-make-your-cms-changes-instant
Demo app will be available soon
Open to any suggestions

### CODE REVIEW

**Comment by SakshiUppoor** [comment]
Relates to https://github.com/appwrite/appwrite/issues/1774

**Review by Meldiron — CHANGES_REQUESTED** [review]
I noticed you open-sourced application you made when writing the article, so let's please link to both article and source code like this:

CleanShot 2021-11-01 at 08 22 44

**Comment by SakshiUppoor** [comment]
Sure, I will move it to the demo app section
The source code is just temporarily stored on BitBucket.
Is it fine if I edit the URL in the future in case I decide to move it to GitHub?

**Comment by christyjacob4** [comment]
@SakshiUppoor  Please resolve the merge conflict 🙂

**Comment by SakshiUppoor** [comment]
On it!
Quick question: If I were to add a link to a hosted demo or update the source code link in the future, could I do so by opening a new PR?

**Comment by SakshiUppoor** [comment]
@christyjacob4 Resolved the merge conflict

**Comment by christyjacob4** [comment]
THANK YOU! All changes merged :partying_face:

Please reach out to me on discord to claim your Hacktoberfest swag

As a way of saying thank you, we would also love to invite you to join the Appwrite organization on GitHub. Please share your GitHub username with us on Discord so that we can add you as a contributor to our organization.

Once added, you can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite membership badge will show up on your personal GitHub profile.

**Comment by SakshiUppoor** [comment]
Will do! Thank you so much!

**Pull request merged**
