### PR TITLE
Appwrite with Dart SDK Tutorial Blog

### PR DESCRIPTION
**Pull request by timothy22000**
For issue:
https://github.com/appwrite/appwrite/issues/2302

Blog post:
https://dev.to/timothy22000/appwrite-with-dart-3knc

Reddit post: https://www.reddit.com/r/programming/comments/qju9kk/using_dart_with_appwrite_which_provides_a_secure/

I had a lot of fun playing around with Appwrite to get content while working on the blogpost :) Let me know if there are any changes that you would like me to make.

### CODE REVIEW

**Review by Meldiron — CHANGES_REQUESTED** [review]
Take a look at this link: https://github.com/appwrite/awesome-appwrite/pull/379/files
You can notice that you changes some lines you didn't mean to. Can we please update the PR to only hold the one line you wanted to add?

**Comment by christyjacob4** [comment]
@timothy22000  please address the merge conflict and we can merge this 👍

**Comment by timothy22000** [comment]
Hi @christyjacob4! Hope you had a great weekend. I merged the latest changes and resolved any conflicts now :D

**Comment by christyjacob4** [comment]
THANK YOU! All changes merged :partying_face:

Please reach out to me on discord to claim your hacktoberfest swag.

As a way of saying thank you, we would also love to invite you to join the Appwrite organization on GitHub. Please share your GitHub username with us on Discord so that we can add you as a contributor to our organization.

Once added, you can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite membership badge will show up on your personal GitHub profile.

**Pull request merged**
