### PR TITLE
Added Appwrite + NextJS blog

### PR DESCRIPTION
**Pull request by qwe123coder**

### CODE REVIEW

**Comment by lohanidamodar** [comment]
@qwe123coder Shows that your repository has been deleted. also the title in readme should be updated as the new title of the blog

**Comment by qwe123coder** [comment]
> @qwe123coder Shows that your repository has been deleted. also the title in readme should be updated as the new title of the blog

omg what i did not delet it let me fix it and also change the title

**Comment by qwe123coder** [comment]
> @qwe123coder Shows that your repository has been deleted. also the title in readme should be updated as the new title of the blog

omg what i did not delet it let me fix it and also change the title

**Review by Meldiron — CHANGES_REQUESTED** [review]
The article is about NextJS meanwhile change in readme is talking about NextJS. Let's please ensure we use the same word everywhere.

**Comment by lohanidamodar** [comment]
Closing in favor of another PR

**Pull request closed without merging**
