### PR TITLE
Add NextJs social media demo

### PR DESCRIPTION
**Pull request by SanjayDevTech**
## What does this PR do?

Adds a NextJs Social media application

## Related PRs and Issues
[🧑‍🏫 Help Developers by Coding Demo of Appwrite + Next JS #4225](https://github.com/appwrite/appwrite/issues/4225)

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes

### CODE REVIEW

**Comment by SanjayDevTech** [comment]
@gewenyu99 please review

**Review by gewenyu99 — CHANGES_REQUESTED** [review]
Screen Shot 2022-10-24 at 4 44 33 PM
I think you're missing a default redirect to the auth page. `localhost:3000` is empty when I try this app 😲

**Comment by gewenyu99** [comment]
Screen Shot 2022-10-24 at 4 44 33 PM
I think you should consider changing how you take appwrite host. I should be able to just paste in the host from here:
Screen Shot 2022-10-24 at 4 50 19 PM

but at the moment, I can't

**Comment by SanjayDevTech** [comment]
@gewenyu99 I have added a redirection based on authentication state.
if the user is not logged in, they will be redirected to /auth, otherwise to /feed.

For the endpoint, I have added the NEXT_PUBLIC_APPWRITE_ENDPOINT environment var.

**Comment by gewenyu99** [comment]
@SanjayDevTech What are the criteria for your password regex? I can't figure out a valid password. Please check that the regex works as you expect and update the warning with the expected format.

**Comment by SanjayDevTech** [comment]
> @SanjayDevTech What are the criteria for your password regex? I can't figure out a valid password. Please check that the regex works as you expect and update the warning with the expected format.

Password must have 8 letters including atleast one Capital, Small, Numeric, Symbol.
I will update this in hint or error message.
👍

**Comment by gewenyu99** [comment]
Screen Shot 2022-10-31 at 11 24 50 AM
Hi @SanjayDevTech 

I am getting the above error when trying to build and run the project now. Is this something you've experienced?

**Comment by PineappleIOnic** [comment]
Thank you so much for the PR 🤩. We're adding the `hacktoberfest-accepted` label to ensure this PR counts towards your Hacktoberfest contributions count. With that said, please stay active on this PR to address any comments once you receive a review. Happy Hacktoberfest! 🎃

**Comment by gewenyu99** [comment]
@SanjayDevTech 👀 Are the updates you mentioned earlier ready for review?

**Comment by SanjayDevTech** [comment]
@PineappleIOnic Thank youu 🍻

**Comment by christyjacob4** [comment]
THANK YOU! All changes merged 🥳

Please reach out to me on our [Discord server](https://appwrite.io/discord) if you would like to claim your Appwrite swags! As a way of saying thank you, we would also love to invite you to join the Appwrite organization on GitHub. Please share your GitHub username with us on Discord.  

You can accept the invite by visiting https://github.com/orgs/appwrite/invitation. By joining our team, you will officially be an Appwrite maintainer on GitHub.

You can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite team membership badge will show up on your personal GitHub profile.

Please feel free to look for more PRs you might be interested in helping with on our long list of [Hacktoberfest friendly issues](https://github.com/search?q=org%3Aappwrite+org%3Autopia-php+org%3Aopen-runtimes+label%3Ahacktoberfest+created%3A%3E2021-01-01+state%3Aopen&type=issues&s=updated&o=asc) and help make Appwrite better :)

**Pull request merged**
