### PR TITLE
write a blog on Appwrite Storage Services

### PR DESCRIPTION
**Pull request by Yashp1210**
I wrote an blog about Appwrite Storage Services . This PR was created to "fix" this(appwrite/appwrite#2299) issue.

The article can be found here(https://dev.to/yashp1210/appwrites-storage-service-ned)

### CODE REVIEW

**Comment by Yashp1210** [comment]
My repo got deleted , so forked again and sent the Pull request

https://github.com/appwrite/awesome-appwrite/pull/393

**Comment by christyjacob4** [comment]
@Yashp1210 Looks like there are some conflicts in your PR. Please fix those for us to merge it

**Comment by Yashp1210** [comment]
@christyjacob4 my repo got deleted , so i forked it again and set the req here 
check here https://github.com/appwrite/awesome-appwrite/pull/393

**Comment by christyjacob4** [comment]
Alright. I'll close this in that case .

**Pull request closed without merging**
