### PR TITLE
added a wallpaper

### PR DESCRIPTION
**Pull request by qwe123coder**
image
made by me and @avinIndrasoma

### CODE REVIEW

**Comment by Meldiron** [comment]
Unfortunately we would not be able to accept your PR as it does not meet some of our criteria around quality. We love contributions, but we suggest you explore any of our [open issues](https://github.com/appwrite/appwrite/issues). If you have any problem or need help, please join our Discord community: https://appwrite.io/discord and use the #hacktoberfest channel.

**Comment by qwe123coder** [comment]
> Unfortunately we would not be able to accept your PR as it does not meet some of our criteria around quality. We love contributions, but we suggest you explore any of our [open issues](https://github.com/appwrite/appwrite/issues). If you have any problem or need help, please join our Discord community: https://appwrite.io/discord and use the #hacktoberfest channel.

Hey idk but for me when I download the quality looks good

**Comment by avinIndrasoma** [comment]
yes, the quality seems really good @Meldiron can you clearly state what the issue is?

**Comment by avinIndrasoma** [comment]
Untitled design (8)
@Meldiron how about now?

**Pull request closed without merging**
