### PR TITLE
Written a Blog Post about Appwrite

### PR DESCRIPTION
**Pull request by priyanshu688**
In this file, I have written the brief intro about Appwrite. How does it works and all the workflow. Link for the post - https://medium.com/@vaishnavipriyanshu198/introducing-appwrite-for-android-best-and-easy-way-to-self-host-d8667598ff1f

### CODE REVIEW

**Comment by lohanidamodar** [comment]
Hey @priyanshu688 awesome work writing the blog post. A couple of suggestions.
1. The authentication provider screen's screenshot used in the blog is a old one please update you can find them [here](https://appwrite.io/assets) (recommended)
2. It would be great if possible to include some code examples from Android app (adding dependency, initializing SDK, authenticating and more if you like). You can check our [getting started for android tutorial](https://appwrite.io/docs/getting-started-for-android). (recommended)
3. If you like you can also help us by sharing the article over social networks, relevant subreddits will provide you an exposure too if you tag @appwrite_io (totally optional)

**Comment by priyanshu688** [comment]
@lohanidamodar yes sure....thanks ..I will do it as soon as possible.

**Comment by priyanshu688** [comment]
@lohanidamodar I have done the changes as per your recommendations. Please check this.

**Comment by Meldiron** [comment]
From a technical point of view, I can see you submitted DOCX file in this PR. Can you please remove that and instead link to the article you wrote in README.md file? There are a bunch of PRs opened currently, you can take inspiration from them. If you need any help, please ask.

**Comment by priyanshu688** [comment]
@Meldiron  Link for the blog - https://medium.com/@vaishnavipriyanshu198/introducing-appwrite-for-android-best-and-easy-way-to-self-host-d8667598ff1f

**Comment by christyjacob4** [comment]
@priyanshu688  I'll be closing this PR for now. Feel free to create a new one when you've addressed the issues

**Pull request closed without merging**
