### PR TITLE
atom and pin added

### PR DESCRIPTION
**Pull request by Yugal41735**
Issue => [Design a new Appwrite Discord emoji 🖌](https://github.com/appwrite/appwrite/issues/2264)

### CODE REVIEW

**Review by Meldiron — CHANGES_REQUESTED** [review]
Few comments:

- To stay consistent with the rest of our Discord emojis, can we make Atom emoji simple - remove the white stroke?
- Pin seems a bit pixelized, can we do something about that? Feel free to submit SVG version and we will export it for Discord

**Comment by Yugal41735** [comment]
@Meldiron  I have improved atom emoji and as for pin emoji, i have added 3 improved images, so tell me if those are correct, if not could u tell me some way, on how to fix pixelated image

**Comment by Yugal41735** [comment]
@Meldiron could u see this, and if any further improvements required do tell me

**Comment by Yugal41735** [comment]
@Meldiron  could u review my recent changes and tell me if any further changes are required

**Comment by Yugal41735** [comment]
@Meldiron if any further changes are required do tell me

**Comment by Yugal41735** [comment]
@Meldiron  I request u to atleast tell me which files are fine, because I also have to remove extra files. So once again I reques u to plz review it. Thank you

**Comment by Yugal41735** [comment]
@Meldiron plz respond??

**Comment by Meldiron** [comment]
To me, all pins still seem blurred. if I draw a circle on top, I can see a difference in the quality. Can we please switch to SVG format? That will take care of it and provide a clean design.

https://user-images.githubusercontent.com/19310830/141317267-546c69ab-9ae9-4bc4-b82f-8fca9d18d67e.mp4

**Comment by Yugal41735** [comment]
final_618c00b6dfb590013ad2cddf_293707 (1)

@Meldiron would u see this and tell me is it fine ?

**Comment by Yugal41735** [comment]
@Meldiron added the svg format of the pin could u plz review it and tell me if it is fine or are there any further improvements required.

**Comment by Yugal41735** [comment]
@Meldiron  I have also added the atom svg, and do tell me which one looks fine

**Comment by Yugal41735** [comment]
@Meldiron  I have added atom svgs with both white fill and transparent background. Do check and tell me.

**Comment by Yugal41735** [comment]
@Meldiron it would be great if u could tell me are there any further improvements required

**Comment by Yugal41735** [comment]
@Meldiron sorry for disturing you on weekend, but if could u review this as I have made some changes.

**Comment by Yugal41735** [comment]
@Meldiron by when could I expect any response, so that I wont ping u everyday

**Comment by Yugal41735** [comment]
@Meldiron ??

**Comment by Yugal41735** [comment]
@Meldiron ??

**Comment by Yugal41735** [comment]
@PineappleIOnic  could u plz review this . I have made the changes asked by @Meldiron.

**Comment by Meldiron** [comment]
- I can see 4 files in the PR, but we only want to add 2 icons, right? Atom and Pin. Let's make sure there are only 2 files - both SVG ideally. I think atom3 is the best one, let's keep that one and rename it to just atom
- Pin SVG has padding, please remove that
CleanShot 2021-11-22 at 12 31 15
You can refer to atom SVG, that one is good, because there is no padding:
CleanShot 2021-11-22 at 12 32 06

**Comment by Yugal41735** [comment]
@Meldiron  done requested changes . And thanku for responding. and once again sorry for pinging u a lot.

**Comment by Yugal41735** [comment]
@Meldiron could u plz review it and tell me. is it now fine?

**Review by Meldiron — APPROVED** [review]
Looks good to me

**Pull request merged**
