### PR TITLE
Add Next.js Users example

### PR DESCRIPTION
**Pull request by RobRuizR**
## What does this PR do?

Adds a demo for Next.js + Appwrite to showcase how to do Auth both on the frontend and on Next.js' Api Routes.

## Related PRs and Issues

[🧑‍🏫 Help Developers by Coding Demo of Appwrite + Next JS ](https://github.com/appwrite/appwrite/issues/4225)

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes!

### CODE REVIEW

**Comment by gewenyu99** [comment]
Woah, this looks awesome! I love how you have detailed instructions and screenshots 💯 

@Meldiron, please take a look when you get some time at the code. I tried the project on Gitpod, seems to work great.

@RobRuizR Would it be possible to add a name field in the form for sign up? Right now I can only sign up as PlaceholderName XD

**Comment by RobRuizR** [comment]
@gewenyu99 for sure!

**Comment by RobRuizR** [comment]
done @gewenyu99!

image
image

**Review by gewenyu99 — APPROVED** [review]
With the name added to the form, I'm happy with this :)

**Review by stnguyen90 — APPROVED** [review]
LGTM!

**Comment by christyjacob4** [comment]
THANK YOU! All changes merged 🥳

Please reach out to me on our [Discord server](https://appwrite.io/discord) if you would like to claim your Appwrite swags! As a way of saying thank you, we would also love to invite you to join the Appwrite organization on GitHub. Please share your GitHub username with us on Discord.  

You can accept the invite by visiting https://github.com/orgs/appwrite/invitation. By joining our team, you will officially be an Appwrite maintainer on GitHub.

You can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite team membership badge will show up on your personal GitHub profile.

Please feel free to look for more PRs you might be interested in helping with on our long list of [Hacktoberfest friendly issues](https://github.com/search?q=org%3Aappwrite+org%3Autopia-php+org%3Aopen-runtimes+label%3Ahacktoberfest+created%3A%3E2021-01-01+state%3Aopen&type=issues&s=updated&o=asc) and help make Appwrite better :)

**Pull request merged**
