### PR TITLE
Add useMindmap project

### PR DESCRIPTION
**Pull request by benweier**
Adds the repo for https://usemindmap.app

_Sorry, my editor config also stripped trailing whitespace from the Markdown_

### CODE REVIEW

**Comment by Haimantika** [comment]
There are some conflicts, can you please fix them?

**Comment by benweier** [comment]
@Haimantika done, thanks :)

**Comment by adityaoberai** [comment]
I've reviewed and fixed the conflict.
Merging the contribution now.

**Comment by adityaoberai** [comment]
Thanks for your contribution @benweier 😁

**Pull request merged**
