### PR TITLE
Added blog for integrating appwrite with google cloud

### PR DESCRIPTION
**Pull request by neelshah2409**
## What does this PR do?
- Had written a blog for beginners that how they can integrate Appwrite with GCP.

## Related PRs and Issues
- https://github.com/appwrite/appwrite/issues/4007

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?
- yes

### CODE REVIEW

**Review by gewenyu99 — CHANGES_REQUESTED** [review]
Hi, @neelshah2409! Thank you for contributing. There's a few things I'd like to point out about this blog that might need to be changed.

1. The paragraphs should be paragraphs on Medium, not bullets.
2. Some of the images and links in the markdown that you added look like they're not rendered correctly, please look again more carefully.
3. The information you added isn't very accurate. Appwrite doesn't have a "free tier", it's self-hosted so it's just free. You also don't need an Appwrite account, you only create an "administrator account" after you've deployed Appwrite. 

Please take a look at these suggestions and request a review after they're addressed.

Thanks!

**Comment by neelshah2409** [comment]
Hii @gewenyu99 ,Thank you for your suggestions ,I have made the changes ,please review the it.

**Comment by gewenyu99** [comment]
Screen Shot 2022-10-31 at 10 48 08 AM
Hi, you still have a broken image in your post

**Comment by neelshah2409** [comment]
> Screen Shot 2022-10-31 at 10 48 08 AM
> 
> Hi, you still have a broken image in your post

Sorry for my silly mistake ,now fixed ,please review it @gewenyu99 !!

**Comment by PineappleIOnic** [comment]
Thank you so much for the PR 🤩. We're adding the `hacktoberfest-accepted` label to ensure this PR counts towards your Hacktoberfest contributions count. With that said, please stay active on this PR to address any comments once you receive a review. Happy Hacktoberfest! 🎃

**Review by gewenyu99 — APPROVED** [review]
Great, thank you for your contribution!

Happy Hacktoberfest ❤️

**Review by christyjacob4 — APPROVED** [review]

**Comment by christyjacob4** [comment]
THANK YOU! All changes merged 🥳

Please reach out to me on our [Discord server](https://appwrite.io/discord) if you would like to claim your Appwrite swags! As a way of saying thank you, we would also love to invite you to join the Appwrite organization on GitHub. Please share your GitHub username with us on Discord.  

You can accept the invite by visiting https://github.com/orgs/appwrite/invitation. By joining our team, you will officially be an Appwrite maintainer on GitHub.

You can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite team membership badge will show up on your personal GitHub profile.

Please feel free to look for more PRs you might be interested in helping with on our long list of [Hacktoberfest friendly issues](https://github.com/search?q=org%3Aappwrite+org%3Autopia-php+org%3Aopen-runtimes+label%3Ahacktoberfest+created%3A%3E2021-01-01+state%3Aopen&type=issues&s=updated&o=asc) and help make Appwrite better :)

**Pull request merged**
