### PR TITLE
added Listr project for hacktoberfest

### PR DESCRIPTION
**Pull request by HelixHEX**
## What does this PR do?
Added Listr project to readme for hacktoberfest

## Test Plan

Only changed the README.md

## Related PRs and Issues

(If this PR is related to any other PR or resolves any issue or related to any issue link all related PR and issues here.)

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes

### CODE REVIEW

**Comment by stnguyen90** [comment]
Related issue:

* https://github.com/appwrite/appwrite/issues/4253

**Review by stnguyen90 — COMMENTED** [review]
Any chance you can add demo to your readme via [snack](https://snack.expo.dev/) or something? For example, there's an [Expo demo](https://expo.dev/@rne_org/react-native-elements) and [Snack](https://snack.expo.dev/@arpitbhalla/react-native-elements) on [this](https://github.com/react-native-elements/react-native-elements) Readme.

**Comment by HelixHEX** [comment]
> Any chance you can add demo to your readme via [snack](https://snack.expo.dev/) or something? For example, there's an [Expo demo](https://expo.dev/@rne_org/react-native-elements) and [Snack](https://snack.expo.dev/@arpitbhalla/react-native-elements) on [this](https://github.com/react-native-elements/react-native-elements) Readme.

Would I need to have a production appwrite server running?

**Comment by stnguyen90** [comment]
> Would I need to have a production appwrite server running?

@HelixHEX, with Snack, you can still update the code so you can have have instructions to tell the user to update certain variables to point to their instance of appwrite.

**Comment by HelixHEX** [comment]
> > Would I need to have a production appwrite server running?
> 
> 
> 
> @HelixHEX, with Snack, you can still update the code so you can have have instructions to tell the user to update certain variables to point to their instance of appwrite.

Alright thanks!

Will do, and I'll add it to the project readme. I'm not sure I'll be able to do it before October ends though.

**Comment by PineappleIOnic** [comment]
Thank you so much for the PR 🤩. We're adding the `hacktoberfest-accepted` label to ensure this PR counts towards your Hacktoberfest contributions count. With that said, please stay active on this PR to address any comments once you receive a review. Happy Hacktoberfest! 🎃

**Review by stnguyen90 — CHANGES_REQUESTED** [review]
Would you please also use the [Appwrite CLI](https://appwrite.io/docs/command-line#gettingStarted) to generate an `appwrite.json` and include the `appwrite.json` in the repo? This will make it easier for users to set up their Appwrite instance for your app.

**Comment by HelixHEX** [comment]
> Would you please also use the [Appwrite CLI](https://appwrite.io/docs/command-line#gettingStarted) to generate an `appwrite.json` and include the `appwrite.json` in the repo? This will make it easier for users to set up their Appwrite instance for your app.
> 
> Also, it would be nice if `APPWRITE_HOSTNAME` were renamed to `APPWRITE_ENDPOINT` since that's the name we use and `HOSTNAME` makes me think of only the hostname rather than the full URL.

I've made the necessary changes

**Review by stnguyen90 — APPROVED** [review]
Hey 👋 awesome work on your PR! We've approved your work and it'll be merged soon!

A snack demo would still be very helpful 😉

**Comment by HelixHEX** [comment]
> Hey 👋 awesome work on your PR! We've approved your work and it'll be merged soon!
> 
> 
> 
> A snack demo would still be very helpful 😉 

Completely forgot about the demo. Will get to it sometime this week or next week!

**Comment by christyjacob4** [comment]
THANK YOU! All changes merged 🥳

Please reach out to me on our [Discord server](https://appwrite.io/discord) if you would like to claim your Appwrite swags! As a way of saying thank you, we would also love to invite you to join the Appwrite organization on GitHub. Please share your GitHub username with us on Discord.  

You can accept the invite by visiting https://github.com/orgs/appwrite/invitation. By joining our team, you will officially be an Appwrite maintainer on GitHub.

You can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite team membership badge will show up on your personal GitHub profile.

Please feel free to look for more PRs you might be interested in helping with on our long list of [Hacktoberfest friendly issues](https://github.com/search?q=org%3Aappwrite+org%3Autopia-php+org%3Aopen-runtimes+label%3Ahacktoberfest+created%3A%3E2021-01-01+state%3Aopen&type=issues&s=updated&o=asc) and help make Appwrite better :)

**Pull request merged**
