### PR TITLE
docs: add cake house example

### PR DESCRIPTION
**Pull request by omeraplak**
## What does this PR do?

A new example has been added to the Showcase section

### CODE REVIEW

**Comment by gewenyu99** [comment]
@omeraplak That's AMAZING!!!

This is great, only question I wanted to ask is which version of Appwrite this is running. The console screenshot looks pretty ancient 😅 

If the integration is still running an old version of Appwrite and the screenshots are correct, I'd still love to approve this PR.

Thanks Omer!

**Comment by PineappleIOnic** [comment]
Thank you so much for the PR 🤩. We're adding the `hacktoberfest-accepted` label to ensure this PR counts towards your Hacktoberfest contributions count. With that said, please stay active on this PR to address any comments once you receive a review. Happy Hacktoberfest! 🎃

**Review by stnguyen90 — CHANGES_REQUESTED** [review]
@omeraplak this is an awesome integration! One problem is it seems the code is outdated. The Live StackBlitz Example looks broken:

image

I'm also getting the same when I try to clone the repo and run the code locally.

**Comment by christyjacob4** [comment]
@omeraplak would you be able to address the comments ?

**Review by christyjacob4 — APPROVED** [review]

**Comment by christyjacob4** [comment]
THANK YOU! All changes merged 🥳

Please reach out to me on our [Discord server](https://appwrite.io/discord) if you would like to claim your Appwrite swags! As a way of saying thank you, we would also love to invite you to join the Appwrite organization on GitHub. Please share your GitHub username with us on Discord.  

You can accept the invite by visiting https://github.com/orgs/appwrite/invitation. By joining our team, you will officially be an Appwrite maintainer on GitHub.

You can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite team membership badge will show up on your personal GitHub profile.

Please feel free to look for more PRs you might be interested in helping with on our long list of [Hacktoberfest friendly issues](https://github.com/search?q=org%3Aappwrite+org%3Autopia-php+org%3Aopen-runtimes+label%3Ahacktoberfest+created%3A%3E2021-01-01+state%3Aopen&type=issues&s=updated&o=asc) and help make Appwrite better :)

**Pull request merged**
