### PR TITLE
Almost Instagram Submission - Flutter + Appwrite

### PR DESCRIPTION
**Pull request by letsintegreat**
## What does this PR do?

I have added a demo project with flutter and appwrite - Almost Instagram.

## Test Plan

Find the installation instructions in the README.md file of the linked repo.

## Related PRs and Issues

This PR was made under this issue:
https://github.com/appwrite/appwrite/issues/4286

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes.

### CODE REVIEW

**Comment by stnguyen90** [comment]
@letsintegreat Thanks for the PR! 🤯 Please give us some time to review it.

**Comment by gewenyu99** [comment]
Yeah @letsintegreat This is an amazing PR. Would love @lohanidamodar to take a look here, too.

I looked through the code base quickly. I might point out that it looks like you're initializing the Appwrite SDK/ Client class multiple times in different places in your code. I think this might be an issue because it's really meant to be initialized once and to have only one instance. (correct me if I'm wrong @stnguyen90)

Check the implementation here: https://github.com/appwrite/demo-almost-netflix-for-flutter (it might be a bit old)

**Comment by letsintegreat** [comment]
@gewenyu99 Thanks for suggesting the changes! I have fixed the usage of Client in this commit - https://github.com/letsintegreat/Almost-Instagram/commit/94d627f2628e04ec088a944f28cb3230803e734d

Now it is initialized only once. Kindly review now, thanks!

**Comment by gewenyu99** [comment]
Let me help you out by requesting reviews from our Flutter experts in case they didn't see this yet :)

**Comment by letsintegreat** [comment]
@gewenyu99 Thanks for bumping this PR up! Though I think you guys are getting a lot of PRs, and I understand if you can't review them right away.

**Review by stnguyen90 — COMMENTED** [review]
Great PR! 🤯 We left some comments during the review, please check them out. 

1. Would you please use the Appwrite CLI to generate an appwrite.json file with your collection and include it in your repo? This will make it easier for others to deploy the collection.
2. Your instructions seem to also be missing instructions about bucket and collection permissions
3. Your instructions are also missing registering the platform

**Comment by letsintegreat** [comment]
@stnguyen90 Hey! Thanks for reviewing the PR. I have addressed all of the three points in this [commit](https://github.com/letsintegreat/Almost-Instagram/commit/2ce94315a9341d0e7fc5a298fe659e0c5ab3354e). I have used Appwrite CLI to generate an appwrite.json file. And the README.md file now contains the entire setup process using Appwrite CLI.

Regarding bucket and collection permissions, they are now handled while creating the bucket and the collection. And I have also added instructions to register the client.

Please, review the PR again and LMK if there's something else that needs to be changed.

**Review by stnguyen90 — APPROVED** [review]
@letsintegreat Hey 👋 awesome work on your PR! We've approved your work and it'll be merged soon!

**Pull request merged**
