### PR TITLE
Add Almost BitLy

### PR DESCRIPTION
**Pull request by SiddharthShyniben**
## What does this PR do?

Adds Almost Bitly (appwrite/appwrite#4307) to the list.

## Test Plan

NA

## Related PRs and Issues

appwrite/appwrite#4307

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes

### CODE REVIEW

**Comment by PineappleIOnic** [comment]
Thank you so much for the PR 🤩. We're adding the `hacktoberfest-accepted` label to ensure this PR counts towards your Hacktoberfest contributions count. With that said, please stay active on this PR to address any comments once you receive a review. Happy Hacktoberfest! 🎃

**Review by adityaoberai — CHANGES_REQUESTED** [review]
Thanks for the submission @SiddharthShyniben 

I was just trying the application. After the short link is generated, the URL does not seem to work. Instead, I get the following error. 
image

I am, however, seeing the entry in the Database, and the Analytics URL is functioning.
image
image

Could you please test your application for this error once?

**Comment by adityaoberai** [comment]
Additionally, could you also mention the recommended size of `id` string for the database here in the [Readme](https://github.com/SiddharthShyniben/almost-bitly/blob/9ee5422b91fd48c26eed9276c2c4c3882df75c90/README.md?plain=1#L19)?

image


And please shift the Appwrite endpoint and project Id to the environment as well instead of hard coding them in the [GenerateService](https://github.com/SiddharthShyniben/almost-bitly/blob/9ee5422b91fd48c26eed9276c2c4c3882df75c90/src/app/services/generate.service.ts#L17)

image

**Comment by christyjacob4** [comment]
@SiddharthShyniben  thanks a lot for your contributions during Hacktoberfest 2022!  

Please reach out to me on our [Discord server](https://appwrite.io/discord) if you would like to claim your Appwrite swags! As a way of saying thank you, we would also love to invite you to join the Appwrite organization on GitHub. Please share your GitHub username with us on Discord. 

I'm closing this PR at the moment as there has been no activity on it for quite a long time. If you'd like to continue working on it, please feel free to create a new PR

**Pull request closed without merging**
