### PR TITLE
Added kubernetes emoji for discord

### PR DESCRIPTION
**Pull request by noviicee**
Added kubernetes emoji for discord.

Links to the issue: [Design a new Appwrite Discord emoji 🖌 #2264](https://github.com/appwrite/appwrite/issues/2264)

Thank you for allowing us to showcase our creative side :)

*Apologies for not renaming branch to feat-discord-emoji-X. Got so excited that I missed it. Will make another PR or rename the branch if it is very necessary :)*

### CODE REVIEW

**Comment by noviicee** [comment]
@lohanidamodar @PineappleIOnic can you check it .
Let me know if any changes are required :D

**Review by Meldiron — CHANGES_REQUESTED** [review]
Can we please remove the white background and replace it with transparent? Currently, the emoji is enclosed inside the white square and it doesn't look good.

**Comment by noviicee** [comment]
> Can we please remove the white background and replace it with transparent? Currently, the emoji is enclosed inside the white square and it doesn't look good.

Sure. On to it 🚀

**Comment by Meldiron** [comment]
THANK YOU! All changes merged 🥳

Please reach out to `eldadfux` on our [Discord server](https://appwrite.io/discord) if you would like to claim your Appwrite swags! As a way of saying thank you, we would also love to invite you to join the Appwrite organization on GitHub. Please share your GitHub username with us on Discord.  

You can accept the invite by visiting https://github.com/orgs/appwrite/invitation. By joining our team, you will officially be an Appwrite maintainer on GitHub.

You can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite team membership badge will show up on your personal GitHub profile.

Please feel free to look for more PRs you might be interested in helping with on our long list of [Hacktoberfest friendly issues](https://github.com/search?q=org%3Aappwrite+org%3Autopia-php+is%3Aissue+label%3Ahacktoberfest+created%3A%3E2021-01-01+is%3Aopen&type=issues) and help make Appwrite better :)

**Comment by noviicee** [comment]
Thank you! @Meldiron . I am glad to contribute, and I hope to contribute even more! 🚀

**Comment by noviicee** [comment]
Hi @Meldiron can you please add the `hacktoberfest-accepted` label.

**Pull request merged**
