### PR TITLE
Added Blood appwrite Wallpaper

### PR DESCRIPTION
**Pull request by Gregor-Davies**
Hello,
I've added my blood themed wallpaper. P.s this is for hacktoberfest

### CODE REVIEW

**Review by Meldiron — CHANGES_REQUESTED** [review]
I can also see Microsoft spaceinvader in this PR while you were only referring to the blood wallpaper. Can we double-check that? Is it supposed to be in this PR?

**Comment by Gregor-Davies** [comment]
Hello,
The reason why the space invader emoji is in this pull request is because when I made that emoji I committed it to main by accident so its been accidentally bundled with all my PR's. If you want I can delete the emoji and close that respected PR.

**Comment by Gregor-Davies** [comment]
Should be fixed now!

**Comment by Meldiron** [comment]
THANK YOU! All changes merged 🥳

Please reach out to `eldadfux` on our [Discord server](https://appwrite.io/discord) if you would like to claim your Appwrite swags! As a way of saying thank you, we would also love to invite you to join the Appwrite organization on GitHub. Please share your GitHub username with us on Discord.  

You can accept the invite by visiting https://github.com/orgs/appwrite/invitation. By joining our team, you will officially be an Appwrite maintainer on GitHub.

You can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite team membership badge will show up on your personal GitHub profile.

Please feel free to look for more PRs you might be interested in helping with on our long list of [Hacktoberfest friendly issues](https://github.com/search?q=org%3Aappwrite+org%3Autopia-php+is%3Aissue+label%3Ahacktoberfest+created%3A%3E2021-01-01+is%3Aopen&type=issues) and help make Appwrite better :)

**Pull request merged**
