### PR TITLE
Update README.md!

### PR DESCRIPTION
**Pull request by TheBinitGhimire**
Signed-off-by: Binit Ghimire <thebinitghimire@gmail.com>

Included an e-book "Appwrite Up and Running"!

### CODE REVIEW

**Review by king-11 — CHANGES_REQUESTED** [review]
In the last line an additional line break character was added which can lead to merge conflict for others please look into it too.

**Comment by TheBinitGhimire** [comment]
Hello @king-11,

Now, I have removed the extra line-break character from the end of the document. Looking forward to your response on this!

Thanks,
@TheBinitGhimire

**Comment by king-11** [comment]
@TheBinitGhimire there is some issue with the last commit it didn't remove the trailing line break it is not showing any new change with that commit.

**Comment by TheBinitGhimire** [comment]
Hi @king-11, would you mind confirming once again now? I just removed another trailing line break character.

**Comment by eldadfux** [comment]
What is the point of this PR? Its seems like you just duplicated the same link and removed the author name.

**Comment by TheBinitGhimire** [comment]
Oh, lol! I thought it was a different book as it didn't mention "by Alejandro Garcia" in the title of the webpage I visited, and I didn't even notice the same URL for the existing entry.

I think this PR is of no use. So, I am closing it. Thank you for reminding!

**Pull request closed without merging**
