### PR TITLE
Added Plain text Ascii art

### PR DESCRIPTION
**Pull request by Gregor-Davies**
Hello, 
I've added my plain text ascii art as mention by Meldrion in:

https://github.com/appwrite/awesome-appwrite/pull/328#pullrequestreview-792942426

Sadly I didn't know quite where to put it so I put it in the wallpaper folder. P.s this is for hacktoberfest

### CODE REVIEW

**Review by Meldiron — CHANGES_REQUESTED** [review]
I can see spaceinvider PNG in this PR, was that supposed to be part of PR? If not, can we please update this PR and remove the PNG?

**Comment by Gregor-Davies** [comment]
Hello,
The reason why the space invader emoji is in this pull request is because when I made that emoji I committed it to main by accident so its been accidentally bundled with all my PR's. If you want I can delete the emoji and close that respected PR.

**Comment by Gregor-Davies** [comment]
Update: This is fixed now!

**Comment by christyjacob4** [comment]
@Gregor-Davies , If you're willing to submit a wallpaper, please submit it as an image and not a `.txt` file.

**Comment by christyjacob4** [comment]
@Gregor-Davies  closing this PR for now. Feel free to reopen it / create a new one when you're ready to start working on it once again.

**Pull request closed without merging**
