### PR TITLE
Added coffee.svg as a discord emoji

### PR DESCRIPTION
**Pull request by Vidushi-Gupta**
Hi! I am happy to submit a discord emoji as a part of the hacktoberfest 2021!
I made a coffee emoji with Appwrite's colors because why not coffee + code xD

Links to the issue: [Design a new Appwrite Discord emoji 🖌 #2264](https://github.com/appwrite/appwrite/issues/2264)

Thank you for allowing us to showcase our creative side :)

### CODE REVIEW

**Review by Meldiron — COMMENTED** [review]
I am not sure about transparent color for cup 🤔  Discord has both dark and light mode and I would be scared if it looks good on both.

**Comment by Vidushi-Gupta** [comment]
Hi @Meldiron, this is how it looks in the dark and light mode. Hope this is fine?

image
image

**Review by Meldiron — APPROVED** [review]
Looks good to me.

**Comment by Meldiron** [comment]
THANK YOU! All changes merged 🥳

Please reach out to `eldadfux` on our [Discord server](https://appwrite.io/discord) if you would like to claim your Appwrite swags! As a way of saying thank you, we would also love to invite you to join the Appwrite organization on GitHub. Please share your GitHub username with us on Discord.  

You can accept the invite by visiting https://github.com/orgs/appwrite/invitation. By joining our team, you will officially be an Appwrite maintainer on GitHub.

You can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite team membership badge will show up on your personal GitHub profile.

Please feel free to look for more PRs you might be interested in helping with on our long list of [Hacktoberfest friendly issues](https://github.com/search?q=org%3Aappwrite+org%3Autopia-php+is%3Aissue+label%3Ahacktoberfest+created%3A%3E2021-01-01+is%3Aopen&type=issues) and help make Appwrite better :)

**Pull request merged**
