### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by und1n3**
Added An Appwrite+Kotlin Android app [Taleia] to generate and save sets of random words, to break the writer's block. It allows log in /log out to save the combinations that you liked.

### CODE REVIEW

**Review by Meldiron — CHANGES_REQUESTED** [review]
In the readme of your repository, let's please update README with instructions on how to set up a project in Appwrite for this application... That should include database setup (you can use JSON export) and functions - if you use any.

**Comment by und1n3** [comment]
Oh sorry I forgot to write it, README updated!!

**Comment by christyjacob4** [comment]
@und1n3 please resolve the merge conflict 🙂 \

**Comment by und1n3** [comment]
> 

Oh that was new, conflict solved! :)

**Comment by christyjacob4** [comment]
THANK YOU! All changes merged :partying_face:

Please reach out to me on discord to claim your Hacktoberfest swag. 

As a way of saying thank you, we would also love to invite you to join the Appwrite organization on GitHub. Please share your GitHub username with us on Discord so that we can add you as a contributor to our organization.

Once added, you can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite membership badge will show up on your personal GitHub profile.

**Pull request merged**
