### PR TITLE
Blog for "Appwrite for Apple"

### PR DESCRIPTION
**Pull request by sapora1**
https://dev.to/sapora/getting-started-for-apple-2l0
For issue  appwrite/appwrite#2289

### CODE REVIEW

**Review by Meldiron — CHANGES_REQUESTED** [review]
I noticed your changes includes 2 new articles, is this on purpose? I am not sure which one to review... 
Anyway, both of them includes code snippets as screenshots. Can we please convert them to code blocks, so people can easily copy&paste them?

**Comment by sapora1** [comment]
> 
> 
> I noticed your changes includes 2 new articles, is this on purpose? I am not sure which one to review... Anyway, both of them includes code snippets as screenshots. Can we please convert them to code blocks, so people can easily copy&paste them?

There is one article for web and one for Apple

**Comment by sapora1** [comment]
Hey @Meldiron please review it.... done with the required changes

**Comment by Meldiron** [comment]
Unfortunately we would not be able to accept your PR as it does not meet some of our criteria around quality. We love contributions, but we suggest you explore any of our [open issues](https://github.com/appwrite/appwrite/issues). If you have any problem or need help, please join our Discord community: https://appwrite.io/discord and use the #hacktoberfest channel.

**Pull request closed without merging**
