### PR TITLE
Remove Flutter Appwrite Login Template

### PR DESCRIPTION
**Pull request by stnguyen90**
I don't think this should be part of this list because the app doesn't really work. For example, I can "log in" successfully even with an  incorrect email and password.

Log in code doesn't check result of log in:

https://github.com/alistairholmes/flutter-appwrite-login/blob/master/lib/ui/login/login.dart#L165-L171

Log in doesn't even return any sort of result or handle the response at all:

https://github.com/alistairholmes/flutter-appwrite-login/blob/master/lib/utils/auth/auth_state.dart#L38-L46

### CODE REVIEW

**Comment by lohanidamodar** [comment]
@stnguyen90 You are right, but we want to give @alistairholmes an opportunity to fix the issues, you can help by creating PR to the repository as well.

If not fixed, we will considering removing it, but we would love the project to be updated and still remain here.

**Comment by dj3364** [comment]
Help for start very much

**Comment by christyjacob4** [comment]
@alistairholmes  Could you please help address some of the issues in your project ? We would love to make sure that the projects in this list are in working order :smiley:

**Comment by lohanidamodar** [comment]
@christyjacob4 I think we should remove this!

**Review by lohanidamodar — APPROVED** [review]

**Comment by adityaoberai** [comment]
Thanks a lot for the contribution @stnguyen90!
I have resolved the conflict caused by the restructuring of this repo's Readme and merged the changes 🥳

**Pull request merged**
